---
http_interactions:
- request:
    method: get
    uri: http://localhost:19090/api/v1/query?query=node_systemd_unit_state%7Bname='xenserver-pv-version.service',state='active'%7D
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Headers:
      - Accept, Authorization, Content-Type, Origin
      Access-Control-Allow-Methods:
      - GET, OPTIONS
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Expose-Headers:
      - Date
      Content-Type:
      - application/json
      Date:
      - Tue, 14 Feb 2017 09:07:03 GMT
      Content-Length:
      - '248'
    body:
      encoding: UTF-8
      string: '{"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"node_systemd_unit_state","instance":"node-exporter3:9100","job":"prometheus","name":"xenserver-pv-version.service","state":"active"},"value":[1487063223.339,"0"]}]}}'
    http_version: 
  recorded_at: Tue, 14 Feb 2017 09:07:03 GMT
- request:
    method: get
    uri: http://localhost:19090/api/v1/query?query=node_systemd_unit_state%7Bname='running.service',state='active'%7D
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Headers:
      - Accept, Authorization, Content-Type, Origin
      Access-Control-Allow-Methods:
      - GET, OPTIONS
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Expose-Headers:
      - Date
      Content-Type:
      - application/json
      Date:
      - Tue, 14 Feb 2017 09:07:03 GMT
      Content-Length:
      - '408'
    body:
      encoding: UTF-8
      string: '{"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"node_systemd_unit_state","instance":"node-exporter2:9100","job":"prometheus","name":"running.service","state":"active"},"value":[1487063223.344,"1"]},{"metric":{"__name__":"node_systemd_unit_state","instance":"node-exporter1:9100","job":"prometheus","name":"running.service","state":"active"},"value":[1487063223.344,"1"]}]}}'
    http_version: 
  recorded_at: Tue, 14 Feb 2017 09:07:03 GMT
- request:
    method: get
    uri: http://localhost:19090/api/v1/query?query=node_systemd_unit_state%7Bname='not-running.service',state='active'%7D
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Headers:
      - Accept, Authorization, Content-Type, Origin
      Access-Control-Allow-Methods:
      - GET, OPTIONS
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Expose-Headers:
      - Date
      Content-Type:
      - application/json
      Date:
      - Tue, 14 Feb 2017 09:07:03 GMT
      Content-Length:
      - '414'
    body:
      encoding: UTF-8
      string: '{"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"node_systemd_unit_state","instance":"node-exporter1:9100","job":"prometheus","name":"not-running.service","state":"active"},"value":[1487063223.35,"0"]},{"metric":{"__name__":"node_systemd_unit_state","instance":"node-exporter2:9100","job":"prometheus","name":"not-running.service","state":"active"},"value":[1487063223.35,"0"]}]}}'
    http_version: 
  recorded_at: Tue, 14 Feb 2017 09:07:03 GMT
- request:
    method: get
    uri: http://localhost:19090/api/v1/query?query=node_systemd_unit_state%7Bname='kube-controller-manager.service',state='active'%7D
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Headers:
      - Accept, Authorization, Content-Type, Origin
      Access-Control-Allow-Methods:
      - GET, OPTIONS
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Expose-Headers:
      - Date
      Content-Type:
      - application/json
      Date:
      - Tue, 14 Feb 2017 09:07:03 GMT
      Content-Length:
      - '63'
    body:
      encoding: UTF-8
      string: '{"status":"success","data":{"resultType":"vector","result":[]}}'
    http_version: 
  recorded_at: Tue, 14 Feb 2017 09:07:03 GMT
- request:
    method: get
    uri: http://localhost:19090/api/v1/query?query=node_systemd_unit_state%7Bname='kube-scheduler.service',state='active'%7D
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Headers:
      - Accept, Authorization, Content-Type, Origin
      Access-Control-Allow-Methods:
      - GET, OPTIONS
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Expose-Headers:
      - Date
      Content-Type:
      - application/json
      Date:
      - Tue, 14 Feb 2017 09:07:03 GMT
      Content-Length:
      - '63'
    body:
      encoding: UTF-8
      string: '{"status":"success","data":{"resultType":"vector","result":[]}}'
    http_version: 
  recorded_at: Tue, 14 Feb 2017 09:07:03 GMT
- request:
    method: get
    uri: http://localhost:19090/api/v1/query?query=node_systemd_unit_state%7Bname='kube-kubelet.service',state='active'%7D
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Headers:
      - Accept, Authorization, Content-Type, Origin
      Access-Control-Allow-Methods:
      - GET, OPTIONS
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Expose-Headers:
      - Date
      Content-Type:
      - application/json
      Date:
      - Tue, 14 Feb 2017 09:07:03 GMT
      Content-Length:
      - '596'
    body:
      encoding: UTF-8
      string: '{"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"node_systemd_unit_state","instance":"node-exporter1:9100","job":"prometheus","name":"kube-kubelet.service","state":"active"},"value":[1487063223.365,"1"]},{"metric":{"__name__":"node_systemd_unit_state","instance":"node-exporter3:9100","job":"prometheus","name":"kube-kubelet.service","state":"active"},"value":[1487063223.365,"1"]},{"metric":{"__name__":"node_systemd_unit_state","instance":"node-exporter2:9100","job":"prometheus","name":"kube-kubelet.service","state":"active"},"value":[1487063223.365,"1"]}]}}'
    http_version: 
  recorded_at: Tue, 14 Feb 2017 09:07:03 GMT
- request:
    method: get
    uri: http://localhost:19090/api/v1/query?query=node_systemd_unit_state%7Bname='kube-proxy.service',state='active'%7D
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Headers:
      - Accept, Authorization, Content-Type, Origin
      Access-Control-Allow-Methods:
      - GET, OPTIONS
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Expose-Headers:
      - Date
      Content-Type:
      - application/json
      Date:
      - Tue, 14 Feb 2017 09:07:03 GMT
      Content-Length:
      - '587'
    body:
      encoding: UTF-8
      string: '{"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"node_systemd_unit_state","instance":"node-exporter1:9100","job":"prometheus","name":"kube-proxy.service","state":"active"},"value":[1487063223.37,"1"]},{"metric":{"__name__":"node_systemd_unit_state","instance":"node-exporter2:9100","job":"prometheus","name":"kube-proxy.service","state":"active"},"value":[1487063223.37,"1"]},{"metric":{"__name__":"node_systemd_unit_state","instance":"node-exporter3:9100","job":"prometheus","name":"kube-proxy.service","state":"active"},"value":[1487063223.37,"1"]}]}}'
    http_version: 
  recorded_at: Tue, 14 Feb 2017 09:07:03 GMT
- request:
    method: get
    uri: http://localhost:19090/api/v1/query?query=100-((node_memory_MemAvailable/node_memory_MemTotal)*100)
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Headers:
      - Accept, Authorization, Content-Type, Origin
      Access-Control-Allow-Methods:
      - GET, OPTIONS
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Expose-Headers:
      - Date
      Content-Type:
      - application/json
      Date:
      - Tue, 14 Feb 2017 09:07:03 GMT
      Content-Length:
      - '394'
    body:
      encoding: UTF-8
      string: '{"status":"success","data":{"resultType":"vector","result":[{"metric":{"instance":"node-exporter2:9100","job":"prometheus"},"value":[1487063223.375,"29.718866272118746"]},{"metric":{"instance":"node-exporter1:9100","job":"prometheus"},"value":[1487063223.375,"41.65704379520997"]},{"metric":{"instance":"node-exporter3:9100","job":"prometheus"},"value":[1487063223.375,"29.718866272118746"]}]}}'
    http_version: 
  recorded_at: Tue, 14 Feb 2017 09:07:03 GMT
- request:
    method: get
    uri: http://localhost:19090/api/v1/query?query=100-((node_filesystem_avail%7Bmountpoint=%22/%22%7D/node_filesystem_size%7Bmountpoint=%22/%22%7D)*100)
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Headers:
      - Accept, Authorization, Content-Type, Origin
      Access-Control-Allow-Methods:
      - GET, OPTIONS
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Expose-Headers:
      - Date
      Content-Type:
      - application/json
      Date:
      - Tue, 14 Feb 2017 09:07:03 GMT
      Content-Length:
      - '553'
    body:
      encoding: UTF-8
      string: '{"status":"success","data":{"resultType":"vector","result":[{"metric":{"device":"/dev/vda9","fstype":"ext4","instance":"node-exporter2:9100","job":"prometheus","mountpoint":"/"},"value":[1487063223.381,"18.17927644150504"]},{"metric":{"device":"/dev/vda9","fstype":"ext4","instance":"node-exporter3:9100","job":"prometheus","mountpoint":"/"},"value":[1487063223.381,"18.17927644150504"]},{"metric":{"device":"/dev/vda9","fstype":"ext4","instance":"node-exporter1:9100","job":"prometheus","mountpoint":"/"},"value":[1487063223.381,"72.7433272408773"]}]}}'
    http_version: 
  recorded_at: Tue, 14 Feb 2017 09:07:03 GMT
- request:
    method: get
    uri: http://localhost:19090/api/v1/query?query=100-((node_filesystem_avail%7Bmountpoint=%22/var/lib/docker%22%7D/node_filesystem_size%7Bmountpoint=%22/var/lib/docker%22%7D)*100)
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Headers:
      - Accept, Authorization, Content-Type, Origin
      Access-Control-Allow-Methods:
      - GET, OPTIONS
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Expose-Headers:
      - Date
      Content-Type:
      - application/json
      Date:
      - Tue, 14 Feb 2017 09:07:03 GMT
      Content-Length:
      - '595'
    body:
      encoding: UTF-8
      string: '{"status":"success","data":{"resultType":"vector","result":[{"metric":{"device":"/dev/vdb","fstype":"ext4","instance":"node-exporter2:9100","job":"prometheus","mountpoint":"/var/lib/docker"},"value":[1487063223.386,"29.620547021108536"]},{"metric":{"device":"/dev/vdb","fstype":"ext4","instance":"node-exporter3:9100","job":"prometheus","mountpoint":"/var/lib/docker"},"value":[1487063223.386,"29.620547021108536"]},{"metric":{"device":"/dev/vdb","fstype":"ext4","instance":"node-exporter1:9100","job":"prometheus","mountpoint":"/var/lib/docker"},"value":[1487063223.386,"87.63801383313366"]}]}}'
    http_version: 
  recorded_at: Tue, 14 Feb 2017 09:07:03 GMT
- request:
    method: get
    uri: http://localhost:19090/api/v1/query?query=sum(node_load5%7Bjob=%22prometheus%22%7D)/count(node_cpu%7Bmode=%22system%22,job=%22prometheus%22%7D)
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Headers:
      - Accept, Authorization, Content-Type, Origin
      Access-Control-Allow-Methods:
      - GET, OPTIONS
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Expose-Headers:
      - Date
      Content-Type:
      - application/json
      Date:
      - Tue, 14 Feb 2017 09:07:03 GMT
      Content-Length:
      - '108'
    body:
      encoding: UTF-8
      string: '{"status":"success","data":{"resultType":"vector","result":[{"metric":{},"value":[1487063223.392,"0.15"]}]}}'
    http_version: 
  recorded_at: Tue, 14 Feb 2017 09:07:03 GMT
- request:
    method: get
    uri: http://localhost:19090/api/v1/query?query=sum(node_load5%7Bjob=%22prometheus%22%7D)/(count(node_cpu%7Bmode=%22system%22,job=%22prometheus%22%7D)-(count(node_cpu%7Bmode=%22system%22,job=%22prometheus%22%7D)/count(node_load5%7Bjob=%22prometheus%22%7D))*1)
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Headers:
      - Accept, Authorization, Content-Type, Origin
      Access-Control-Allow-Methods:
      - GET, OPTIONS
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Expose-Headers:
      - Date
      Content-Type:
      - application/json
      Date:
      - Tue, 14 Feb 2017 09:07:03 GMT
      Content-Length:
      - '121'
    body:
      encoding: UTF-8
      string: '{"status":"success","data":{"resultType":"vector","result":[{"metric":{},"value":[1487063223.4,"0.22499999999999998"]}]}}'
    http_version: 
  recorded_at: Tue, 14 Feb 2017 09:07:03 GMT
- request:
    method: get
    uri: http://localhost:19090/api/v1/query?query=up
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Headers:
      - Accept, Authorization, Content-Type, Origin
      Access-Control-Allow-Methods:
      - GET, OPTIONS
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Expose-Headers:
      - Date
      Content-Type:
      - application/json
      Date:
      - Tue, 14 Feb 2017 09:07:03 GMT
      Content-Length:
      - '389'
    body:
      encoding: UTF-8
      string: '{"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"up","instance":"node-exporter2:9100","job":"prometheus"},"value":[1487063223.41,"1"]},{"metric":{"__name__":"up","instance":"node-exporter1:9100","job":"prometheus"},"value":[1487063223.41,"1"]},{"metric":{"__name__":"up","instance":"node-exporter3:9100","job":"prometheus"},"value":[1487063223.41,"1"]}]}}'
    http_version: 
  recorded_at: Tue, 14 Feb 2017 09:07:03 GMT
- request:
    method: get
    uri: http://localhost:19090/api/v1/query?query=max_over_time(node_uname_info%5B1d%5D)
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Headers:
      - Accept, Authorization, Content-Type, Origin
      Access-Control-Allow-Methods:
      - GET, OPTIONS
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Expose-Headers:
      - Date
      Content-Type:
      - application/json
      Date:
      - Tue, 14 Feb 2017 09:07:03 GMT
      Content-Length:
      - '860'
    body:
      encoding: UTF-8
      string: '{"status":"success","data":{"resultType":"vector","result":[{"metric":{"domainname":"(none)","instance":"node-exporter2:9100","job":"prometheus","machine":"x86_64","nodename":"sbppapik8s-worker2","release":"4.5.0-coreos-r1","sysname":"Linux","version":"#2
        SMP Tue May 24 17:45:36 UTC 2016"},"value":[1487063223.415,"1"]},{"metric":{"domainname":"(none)","instance":"node-exporter1:9100","job":"prometheus","machine":"x86_64","nodename":"sbppapik8s-worker1.fakedomain.tld","release":"4.5.0-coreos-r1","sysname":"Linux","version":"#2
        SMP Tue May 24 17:45:36 UTC 2016"},"value":[1487063223.415,"1"]},{"metric":{"domainname":"(none)","instance":"node-exporter3:9100","job":"prometheus","machine":"x86_64","nodename":"sbppapik8s-worker3","release":"4.5.0-coreos-r1","sysname":"Linux","version":"#2
        SMP Tue May 24 17:45:36 UTC 2016"},"value":[1487063223.415,"1"]}]}}'
    http_version: 
  recorded_at: Tue, 14 Feb 2017 09:07:03 GMT
recorded_with: VCR 3.0.3
