version: '2'

networks:
  default:
    external:
      name: check_prometheus

services:
  promtheues:
    build:
      dockerfile: $PWD/dockerfiles/prometheus
      context: ./prometheus/
    container_name: prometheus
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
    expose:
      - 19090
    ports:
      - 19090:9090
  node-exporter1:
    build:
      dockerfile: $PWD/dockerfiles/node
      context: ./node-exporter/node1
    expose:
      - 19100
    ports:
      - 19100:9100
    command:
      - "-collectors.enabled=textfile"
      - "-collector.textfile.directory=/etc/node-exporter/"
  node-exporter2:
    build:
      dockerfile: $PWD/dockerfiles/node
      context: ./node-exporter/node2
    expose:
      - 19101
    ports:
      - 19101:9100
    command:
      - "-collectors.enabled=textfile"
      - "-collector.textfile.directory=/etc/node-exporter/"
  node-exporter3:
    build:
      dockerfile: $PWD/dockerfiles/node
      context: ./node-exporter/node3
    expose:
      - 19102
    ports:
      - 19102:9100
    command:
      - "-collectors.enabled=textfile"
      - "-collector.textfile.directory=/etc/node-exporter/"
