---
http_interactions:
- request:
    method: get
    uri: http://localhost:19090/api/v1/query?query=up
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Headers:
      - Accept, Authorization, Content-Type, Origin
      Access-Control-Allow-Methods:
      - GET, OPTIONS
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Expose-Headers:
      - Date
      Content-Type:
      - application/json
      Date:
      - Thu, 23 Feb 2017 17:22:07 GMT
      Content-Length:
      - '392'
    body:
      encoding: UTF-8
      string: '{"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"up","instance":"node-exporter2:9100","job":"prometheus"},"value":[1487870527.639,"1"]},{"metric":{"__name__":"up","instance":"node-exporter1:9100","job":"prometheus"},"value":[1487870527.639,"1"]},{"metric":{"__name__":"up","instance":"node-exporter3:9100","job":"prometheus"},"value":[1487870527.639,"1"]}]}}'
    http_version: 
  recorded_at: Thu, 23 Feb 2017 17:22:07 GMT
- request:
    method: get
    uri: http://127.0.0.1:19090/api/v1/query?query=up
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Headers:
      - Accept, Authorization, Content-Type, Origin
      Access-Control-Allow-Methods:
      - GET, OPTIONS
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Expose-Headers:
      - Date
      Content-Type:
      - application/json
      Date:
      - Sun, 26 Feb 2017 12:05:44 GMT
      Content-Length:
      - '392'
    body:
      encoding: UTF-8
      string: '{"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"up","instance":"node-exporter1:9100","job":"prometheus"},"value":[1488110744.523,"1"]},{"metric":{"__name__":"up","instance":"node-exporter3:9100","job":"prometheus"},"value":[1488110744.523,"1"]},{"metric":{"__name__":"up","instance":"node-exporter2:9100","job":"prometheus"},"value":[1488110744.523,"1"]}]}}'
    http_version: 
  recorded_at: Sun, 26 Feb 2017 12:05:44 GMT
recorded_with: VCR 3.0.3
