---
http_interactions:
- request:
    method: get
    uri: http://localhost:19090/api/v1/query?query=100-((node_filesystem_files_free%7Bfstype!~%22tmpfs%22%7D/node_filesystem_files%7Bfstype!~%22tmpfs%22%7D)*100)
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Headers:
      - Accept, Authorization, Content-Type, Origin
      Access-Control-Allow-Methods:
      - GET, OPTIONS
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Expose-Headers:
      - Date
      Content-Type:
      - application/json
      Date:
      - Thu, 23 Feb 2017 13:21:51 GMT
      Transfer-Encoding:
      - chunked
    body:
      encoding: UTF-8
      string: '{"status":"success","data":{"resultType":"vector","result":[{"metric":{"device":"/dev/vda1","fstype":"vfat","instance":"node-exporter3:9100","job":"prometheus","mountpoint":"/boot"},"value":[1487856111.85,"NaN"]},{"metric":{"device":"/dev/vdb","fstype":"ext4","instance":"node-exporter2:9100","job":"prometheus","mountpoint":"/var/lib/docker"},"value":[1487856111.85,"8.962240219116211"]},{"metric":{"device":"/dev/vdb","fstype":"ext4","instance":"node-exporter3:9100","job":"prometheus","mountpoint":"/var/lib/docker"},"value":[1487856111.85,"8.962240219116211"]},{"metric":{"device":"/dev/vda6","fstype":"ext4","instance":"node-exporter2:9100","job":"prometheus","mountpoint":"/usr/share/oem"},"value":[1487856111.85,"0.0518798828125"]},{"metric":{"device":"/dev/vda3","fstype":"ext4","instance":"node-exporter3:9100","job":"prometheus","mountpoint":"/usr"},"value":[1487856111.85,"5.744032972440948"]},{"metric":{"device":"/dev/vdb","fstype":"ext4","instance":"node-exporter1:9100","job":"prometheus","mountpoint":"/var/lib/docker"},"value":[1487856111.85,"8.962240219116211"]},{"metric":{"device":"systemd-1","fstype":"autofs","instance":"node-exporter2:9100","job":"prometheus","mountpoint":"/boot"},"value":[1487856111.85,"NaN"]},{"metric":{"device":"/dev/vda1","fstype":"vfat","instance":"node-exporter2:9100","job":"prometheus","mountpoint":"/boot"},"value":[1487856111.85,"NaN"]},{"metric":{"device":"systemd-1","fstype":"autofs","instance":"node-exporter1:9100","job":"prometheus","mountpoint":"/boot"},"value":[1487856111.85,"NaN"]},{"metric":{"device":"/dev/vda6","fstype":"ext4","instance":"node-exporter1:9100","job":"prometheus","mountpoint":"/usr/share/oem"},"value":[1487856111.85,"0.0518798828125"]},{"metric":{"device":"/dev/vda9","fstype":"ext4","instance":"node-exporter2:9100","job":"prometheus","mountpoint":"/"},"value":[1487856111.85,"0.7120942748830856"]},{"metric":{"device":"/dev/vda9","fstype":"ext4","instance":"node-exporter1:9100","job":"prometheus","mountpoint":"/"},"value":[1487856111.85,"0.7120942748830856"]},{"metric":{"device":"/dev/vda9","fstype":"ext4","instance":"node-exporter3:9100","job":"prometheus","mountpoint":"/"},"value":[1487856111.85,"0.7120942748830856"]},{"metric":{"device":"/dev/vda1","fstype":"vfat","instance":"node-exporter1:9100","job":"prometheus","mountpoint":"/boot"},"value":[1487856111.85,"NaN"]},{"metric":{"device":"/dev/vda3","fstype":"ext4","instance":"node-exporter2:9100","job":"prometheus","mountpoint":"/usr"},"value":[1487856111.85,"5.744032972440948"]},{"metric":{"device":"systemd-1","fstype":"autofs","instance":"node-exporter3:9100","job":"prometheus","mountpoint":"/boot"},"value":[1487856111.85,"NaN"]},{"metric":{"device":"/dev/vda6","fstype":"ext4","instance":"node-exporter3:9100","job":"prometheus","mountpoint":"/usr/share/oem"},"value":[1487856111.85,"0.0518798828125"]},{"metric":{"device":"/dev/vda3","fstype":"ext4","instance":"node-exporter1:9100","job":"prometheus","mountpoint":"/usr"},"value":[1487856111.85,"5.744032972440948"]}]}}'
    http_version: 
  recorded_at: Thu, 23 Feb 2017 13:21:51 GMT
- request:
    method: get
    uri: http://127.0.0.1:19090/api/v1/query?query=100-((node_filesystem_files_free%7Bfstype!~%22tmpfs%22%7D/node_filesystem_files%7Bfstype!~%22tmpfs%22%7D)*100)
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Headers:
      - Accept, Authorization, Content-Type, Origin
      Access-Control-Allow-Methods:
      - GET, OPTIONS
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Expose-Headers:
      - Date
      Content-Type:
      - application/json
      Date:
      - Sun, 26 Feb 2017 12:05:44 GMT
      Transfer-Encoding:
      - chunked
    body:
      encoding: UTF-8
      string: '{"status":"success","data":{"resultType":"vector","result":[{"metric":{"device":"/dev/vda6","fstype":"ext4","instance":"node-exporter3:9100","job":"prometheus","mountpoint":"/usr/share/oem"},"value":[1488110744.552,"0.0518798828125"]},{"metric":{"device":"systemd-1","fstype":"autofs","instance":"node-exporter1:9100","job":"prometheus","mountpoint":"/boot"},"value":[1488110744.552,"NaN"]},{"metric":{"device":"/dev/vda1","fstype":"vfat","instance":"node-exporter3:9100","job":"prometheus","mountpoint":"/boot"},"value":[1488110744.552,"NaN"]},{"metric":{"device":"/dev/vda6","fstype":"ext4","instance":"node-exporter2:9100","job":"prometheus","mountpoint":"/usr/share/oem"},"value":[1488110744.552,"0.0518798828125"]},{"metric":{"device":"/dev/vda3","fstype":"ext4","instance":"node-exporter1:9100","job":"prometheus","mountpoint":"/usr"},"value":[1488110744.552,"5.744032972440948"]},{"metric":{"device":"/dev/vdb","fstype":"ext4","instance":"node-exporter3:9100","job":"prometheus","mountpoint":"/var/lib/docker"},"value":[1488110744.552,"8.962240219116211"]},{"metric":{"device":"/dev/vda9","fstype":"ext4","instance":"node-exporter3:9100","job":"prometheus","mountpoint":"/"},"value":[1488110744.552,"0.7120942748830856"]},{"metric":{"device":"/dev/vda1","fstype":"vfat","instance":"node-exporter2:9100","job":"prometheus","mountpoint":"/boot"},"value":[1488110744.552,"NaN"]},{"metric":{"device":"/dev/vda3","fstype":"ext4","instance":"node-exporter2:9100","job":"prometheus","mountpoint":"/usr"},"value":[1488110744.552,"5.744032972440948"]},{"metric":{"device":"/dev/vda9","fstype":"ext4","instance":"node-exporter2:9100","job":"prometheus","mountpoint":"/"},"value":[1488110744.552,"0.7120942748830856"]},{"metric":{"device":"/dev/vdb","fstype":"ext4","instance":"node-exporter1:9100","job":"prometheus","mountpoint":"/var/lib/docker"},"value":[1488110744.552,"8.962240219116211"]},{"metric":{"device":"systemd-1","fstype":"autofs","instance":"node-exporter3:9100","job":"prometheus","mountpoint":"/boot"},"value":[1488110744.552,"NaN"]},{"metric":{"device":"/dev/vda1","fstype":"vfat","instance":"node-exporter1:9100","job":"prometheus","mountpoint":"/boot"},"value":[1488110744.552,"NaN"]},{"metric":{"device":"/dev/vda3","fstype":"ext4","instance":"node-exporter3:9100","job":"prometheus","mountpoint":"/usr"},"value":[1488110744.552,"5.744032972440948"]},{"metric":{"device":"systemd-1","fstype":"autofs","instance":"node-exporter2:9100","job":"prometheus","mountpoint":"/boot"},"value":[1488110744.552,"NaN"]},{"metric":{"device":"/dev/vda9","fstype":"ext4","instance":"node-exporter1:9100","job":"prometheus","mountpoint":"/"},"value":[1488110744.552,"0.7120942748830856"]},{"metric":{"device":"/dev/vda6","fstype":"ext4","instance":"node-exporter1:9100","job":"prometheus","mountpoint":"/usr/share/oem"},"value":[1488110744.552,"0.0518798828125"]},{"metric":{"device":"/dev/vdb","fstype":"ext4","instance":"node-exporter2:9100","job":"prometheus","mountpoint":"/var/lib/docker"},"value":[1488110744.552,"8.962240219116211"]}]}}'
    http_version: 
  recorded_at: Sun, 26 Feb 2017 12:05:44 GMT
recorded_with: VCR 3.0.3
