---
http_interactions:
- request:
    method: get
    uri: http://localhost:19090/api/v1/query?query=node_systemd_unit_state%7Bname='running.service',state=''%7D
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Headers:
      - Accept, Authorization, Content-Type, Origin
      Access-Control-Allow-Methods:
      - GET, OPTIONS
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Expose-Headers:
      - Date
      Content-Type:
      - application/json
      Date:
      - Thu, 23 Feb 2017 13:56:01 GMT
      Content-Length:
      - '63'
    body:
      encoding: UTF-8
      string: '{"status":"success","data":{"resultType":"vector","result":[]}}'
    http_version: 
  recorded_at: Thu, 23 Feb 2017 13:56:01 GMT
- request:
    method: get
    uri: http://localhost:19090/api/v1/query?query=node_systemd_unit_state%7Bname='running.service',state='active'%7D
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Headers:
      - Accept, Authorization, Content-Type, Origin
      Access-Control-Allow-Methods:
      - GET, OPTIONS
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Expose-Headers:
      - Date
      Content-Type:
      - application/json
      Date:
      - Thu, 23 Feb 2017 13:58:19 GMT
      Content-Length:
      - '408'
    body:
      encoding: UTF-8
      string: '{"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"node_systemd_unit_state","instance":"node-exporter1:9100","job":"prometheus","name":"running.service","state":"active"},"value":[1487858299.557,"1"]},{"metric":{"__name__":"node_systemd_unit_state","instance":"node-exporter2:9100","job":"prometheus","name":"running.service","state":"active"},"value":[1487858299.557,"1"]}]}}'
    http_version: 
  recorded_at: Thu, 23 Feb 2017 13:58:19 GMT
- request:
    method: get
    uri: http://127.0.0.1:19090/api/v1/query?query=node_systemd_unit_state%7Bname='running.service',state='active'%7D
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Headers:
      - Accept, Authorization, Content-Type, Origin
      Access-Control-Allow-Methods:
      - GET, OPTIONS
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Expose-Headers:
      - Date
      Content-Type:
      - application/json
      Date:
      - Sun, 26 Feb 2017 12:05:44 GMT
      Content-Length:
      - '408'
    body:
      encoding: UTF-8
      string: '{"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"node_systemd_unit_state","instance":"node-exporter2:9100","job":"prometheus","name":"running.service","state":"active"},"value":[1488110744.617,"1"]},{"metric":{"__name__":"node_systemd_unit_state","instance":"node-exporter1:9100","job":"prometheus","name":"running.service","state":"active"},"value":[1488110744.617,"1"]}]}}'
    http_version: 
  recorded_at: Sun, 26 Feb 2017 12:05:44 GMT
recorded_with: VCR 3.0.3
