---
http_interactions:
- request:
    method: get
    uri: http://localhost:19090/api/v1/query?query=(count(node_cpu%7Bmode=%22system%22%7D)by(instance))
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Headers:
      - Accept, Authorization, Content-Type, Origin
      Access-Control-Allow-Methods:
      - GET, OPTIONS
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Expose-Headers:
      - Date
      Content-Type:
      - application/json
      Date:
      - Tue, 14 Feb 2017 06:56:25 GMT
      Content-Length:
      - '287'
    body:
      encoding: UTF-8
      string: '{"status":"success","data":{"resultType":"vector","result":[{"metric":{"instance":"node-exporter2:9100"},"value":[1487055385.984,"2"]},{"metric":{"instance":"node-exporter1:9100"},"value":[1487055385.984,"2"]},{"metric":{"instance":"node-exporter3:9100"},"value":[1487055385.984,"2"]}]}}'
    http_version: 
  recorded_at: Tue, 14 Feb 2017 06:56:25 GMT
- request:
    method: get
    uri: http://localhost:19090/api/v1/query?query=node_load5
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Headers:
      - Accept, Authorization, Content-Type, Origin
      Access-Control-Allow-Methods:
      - GET, OPTIONS
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Expose-Headers:
      - Date
      Content-Type:
      - application/json
      Date:
      - Tue, 14 Feb 2017 06:56:25 GMT
      Content-Length:
      - '419'
    body:
      encoding: UTF-8
      string: '{"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"node_load5","instance":"node-exporter1:9100","job":"prometheus"},"value":[1487055385.99,"0.3"]},{"metric":{"__name__":"node_load5","instance":"node-exporter3:9100","job":"prometheus"},"value":[1487055385.99,"0.3"]},{"metric":{"__name__":"node_load5","instance":"node-exporter2:9100","job":"prometheus"},"value":[1487055385.99,"0.3"]}]}}'
    http_version: 
  recorded_at: Tue, 14 Feb 2017 06:56:25 GMT
recorded_with: VCR 3.0.3
